apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate 
metadata:
  name: hello-world 
  namespace: workflows
spec:
  entrypoint: hello-world
  serviceAccountName: workflow-executor
  templates:
    - name: hello-world
      container:
        image: busybox
        command: [ echo ]
        args: [ "hello world" ]
        resources:
          limits:
            memory: 32Mi
            cpu: 100m