apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "mariadb-parent-app"
  namespace: argocd
spec:
  project: {{ .Values.projectName }}
  source:
    repoURL: https://github.com/krzysiekpagacz/argocd-playground.git
    targetRevision: {{ .Values.targetRevision }}
    path: apps/child-apps
    helm:
      valuesObject: {{ $.Values | toYaml | nindent 8}}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 30
      backof:
        duration: 1m
        factor: 2
        maxDuration: 5m
