
mariadb-cluster:
  mariadb:
    replicas: 1
    galera:
      enabled: false
    podSecurityContext:
      runAsUser: 0
    rootPasswordSecretKeyRef:
      name: mariadb
      key: root-password
      generate: true
    storage:
      size: 1Gi


