{{/* The subchart used to feed the calling chart with values for the mariadb-cluster chart */}}
{{/* Full values reference https://github.com/mariadb-operator/mariadb-operator/blob/main/deploy/charts/mariadb-cluster/values.yaml */}}
{{- define "mariadbCluster.computedValues" -}}
{{- $cluster := default (dict) .Values.cluster -}}
{{- $rootPass := default (dict) $cluster.rootPasswordSecretKeyRef -}}
{{- $galeraEnabled := default false (or $cluster.galeraEnabled (and (hasKey $cluster "galera") (get $cluster.galera "enabled"))) -}}

nameOverride: {{ .Values.clusterName }}
mariadb:
  rootPasswordSecretKeyRef:
    name: {{ default "mariadb" $rootPass.name | quote }}
    key:  {{ default "root-password" $rootPass.key | quote }}
    generate: true

  storage:
    size: 1Gi
  replicas: {{ default 3 $cluster.replicas }}
  galera:
    enabled: {{ $galeraEnabled }}

  # for the MariaDB cluster bootstrapping it is required to have access to the Volume owned by root user, hence runAsUser=0
  # once cluster is up and runnning switch back to the user 999.
  # ToDo(kp): think about nicer solution to do that 
  podSecurityContext:
    runAsUser: 0
  # podSecurityContext:
  #   runAsNonRoot: true
  #   runAsUser: 999
  #   runAsGroup: 999
  #   fsGroup: 999

  metrics:
    enabled: {{ default false $cluster.metricsEnabled }}

  tls:
    enabled: {{ default false $cluster.tlsEnabled }} #ToDo(kp): make default to true before merge

databases:
- name: {{ .Values.databaseName }}

users:
  - name: admin
    passwordSecretKeyRef:
      name: admin-password
      key: password
    host: "%"

grants:
  - name: admin-all
    privileges:
      - "ALL PRIVILEGES"
    database: "*"
    table: "*"
    username: admin
    host: "%"
    grantOption: true


{{- end -}}
