{{/* The subchart used to feed the calling chart with values for the mariadb-cluster chart */}}
{{/* Full values reference https://github.com/mariadb-operator/mariadb-operator/blob/main/deploy/charts/mariadb-cluster/README.md */}}
{{- define "mariadbCluster.computedValues" -}}
{{- $cluster := default (dict) .Values.cluster -}}
{{- $rootPass := default (dict) $cluster.rootPasswordSecretKeyRef -}}
{{- $galeraEnabled := default false (or $cluster.galeraEnabled (and (hasKey $cluster "galera") (get $cluster.galera "enabled"))) -}}

mariadb:
  rootPasswordSecretKeyRef:
    name: {{ default "mariadb" $rootPass.name | quote }}
    key:  {{ default "root-password" $rootPass.key | quote }}
    generate: true

  storage:
    size: 1Gi
  replicas: {{ default 3 $cluster.replicas }}
  galera:
    enabled: {{ $galeraEnabled }}

  # for the MariaDB cluster bootstrapping it is required to have access to the Volume owned by root user, hence runAsUser=0
  # once cluster is up and runnning switch back to the user 999.
  # ToDo(kp): think about nicer solution to do that 
  # podSecurityContext:
  #   runAsUser: 0
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999

  {{- if $cluster.myCnf }}
  myCnf: {{ nindent 4 $cluster.myCnf }}
  {{- else }}
  # some defaults
  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1600M
    max_allowed_packet=256M
  {{- end }}



  metrics:
    enabled: {{ default false $cluster.metricsEnabled }}

  tls:
    enabled: {{ default false $cluster.tlsEnabled }} #ToDo(kp): make default to true before merge


{{- end -}}
