apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.databaseName }}-cluster"
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: {{ .Values.projectName }}
  source:
    repoURL: https://github.com/krzysiekpagacz/argocd-playground.git
    targetRevision: {{ .Values.targetRevision }}
    path: charts/mariadb-cluster
    helm:
      valuesObject:
        mariadb-cluster: 
        {{- include "mariadbCluster.computedValues" . | nindent 10 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
